version: '2'

services:
  news-api:
    image: 'news-api-image:latest'
    build: news-api\
    container_name: news-api
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-news-test:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  news-ingestion:
    image: 'news-ingestion-image:latest'
    build: news-ingestion\
    container_name: news-ingestion
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-news-test:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:14.3-alpine'
    container_name: postgres-news-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin